default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kittygram_development

test:
  <<: *default
  database: kittygram_test

production:
  <<: *default
  database: kittygram_production
  username: kittygram
  password: <%= ENV['KITTYGRAM_DATABASE_PASSWORD'] %>
